### ISSUE TITLE
Does not load in latest neovim

### ISSUE THREAD

**Issue by IngoMeyer441** [bfrg/vim-cmake-help#1]
Thanks for this useful plugin. Unfortunately, it does not load in latest NeoVim because vim patch `8.1.2250` is not included in NeoVim (yet?). Is it really necessary to require this patch for this plugin to work?

**Comment by IngoMeyer441** [comment]
Ok, it seems the plugin is not compatible with Neovim at all because of the Vim's 8 incompatible job control API. :disappointed:

**Comment by bfrg** [comment]
Oops, sorry for not answering earlier. Somehow I didn't see this issue, or I completely forgot about it, I don't remember.

Unfortunately, Vim and Neovim have diverged too much at this point. It would be very time consuming to keep up to date with both editors (in my opinion). And I don't even use Neovim, so I couldn't help with that part. It seems, nowadays everyone writes Neovim plugins in Lua anyway. You might want to look into that.

Besides, Vim 9 is close to being released which will come with a very polished vim9script language that is quite different from the current vimscript. I have just opened a pull request for it and will merge it once Vim 9 is officially released.
